### PR TITLE
[chore] Add grpc instrumentation e2e test

### LINKED ISSUE #85: add fixture-based e2e test for grpc instrumentation
**Is your feature request related to a problem? Please describe.**

As mentioned in #46 
> I added sample apps for gorillamux and net/http. If someone else wants to add a gRPC app, I think the first 2 serve as a good example. New libraries should be able to drop in similarly.

**Describe the solution you'd like**

A sample app for gRPC instrumentation with similar behavior to the gorillamux and nethttp example apps, with a test to verify output.

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Add e2e test for grpc instrumentation.

- Close #85

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
I've tested the app runs and calls the grpc server. Do we know for sure grpc instrumentation is working?

**Comment by JamieDanielson** [comment]
> I've tested the app runs and calls the grpc server. Do we know for sure grpc instrumentation is working?

No, we don't 😄  Check out #78 . That was the main drive behind wanting a test on this sooner than later. Did you create the `traces.json` part of the test from scratch based on the others?

**Comment by damemi** [comment]
Looks like the sample job is timing out in the CI failure: https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4811053910/jobs/8564536923?pr=106#step:15:5

Checking out your branch and running `make fixture-grpc` on my machine, the Pod logs appear to have the same error that @JamieDanielson pointed out in #78:

```
$ kubectl logs pod/sample-job-4prmc -c auto-instrumentation
...
{"level":"error","ts":1682607535.4222052,"caller":"instrumentors/runner.go:86","msg":"error while loading instrumentors, cleaning up","name":"google.golang.org/grpc","error":"field UprobeHttp2ClientCreateHeaderFields: program uprobe_Http2Client_CreateHeaderFields: load program: permission denied: ;: 977: (07) r6 += -384 (truncated, 1060 line(s) omitted)","stacktrace":"go.opentelemetry.io/auto/pkg/instrumentors.(*instrumentorsManager).load\n\t/app/pkg/instrumentors/runner.go:86\ngo.opentelemetry.io/auto/pkg/instrumentors.(*instrumentorsManager).Run\n\t/app/pkg/instrumentors/runner.go:34\nmain.main\n\t/app/cli/main.go:86\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1682607535.4222748,"caller":"grpc/probe.go:228","msg":"closing gRPC instrumentor"}
{"level":"error","ts":1682607535.4222934,"caller":"cli/main.go:88","msg":"error while running instrumentors","error":"field UprobeHttp2ClientCreateHeaderFields: program uprobe_Http2Client_CreateHeaderFields: load program: permission denied: ;: 977: (07) r6 += -384 (truncated, 1060 line(s) omitted)","stacktrace":"main.main\n\t/app/cli/main.go:88\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**Comment by MikeGoldsmith** [comment]
Also blocked by:
- #135

**Comment by MikeGoldsmith** [comment]
Going to wait for #150 as it resolves part of the issue I was working through. The content of the traces json still has some fixes that we'll need to resolve.

**Pull request closed without merging**
