### PR TITLE
eBPF based instrumentation

### PR DESCRIPTION
**Pull request by edeNFed**
This is an exact copy of: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/4
Signing the commits messed up the previous PR somehow.

### CODE REVIEW

**Review by pdelewski — APPROVED** [review]

**Comment by edeNFed** [comment]
The commits in the previous PR were not signed, so merging was blocked.
I had to do `git push --force` on my fork to sign the commits, which closed the previous PR.
I tried fixing it before opening a new one but without luck 😞 

I configured my git to auto-sign every commit, so this will not happen again.

**Comment by pellared** [comment]
> `git push --force` on my fork to sign the commits, which closed the previous PR.

This is unusual. It is the common way to handle lack of signatures.

Aren't you able to do anything with the "go-instrumentation-maintainers" powers? I think that "maintainers" are usually repository admins.

**Comment by pellared** [comment]
This is strange.

I found that it can happen if one force-pushed after closing the PR (https://github.com/isaacs/github/issues/361), This is the first time I see such an issue it may be good to keep 👀 on it.

**Review by pellared — APPROVED** [review]
Per https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/4#issuecomment-1315535916:

> I am approving as I think that this PR is too big to process it in a regular way. I suggest merging it as it is. People can always look at this PR and add comments. We may address comments as separate PRs

**Pull request merged**
