### PR TITLE
Release v0.2.1-alpha

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
### Fixed

- Fix gRPC instrumentation memory access issue on newer kernels. ([#150](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/150))
- Fix missing spans in gorillamux instrumentation. ([#86](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/86))

### Changed

- Update HTTP span names to include method and route to match semantic conventions. ([#143](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/143))

### CODE REVIEW

**Comment by pellared** [comment]
I suggest removing the following line from changelog https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/a12d31ccb6ed15e7ce073a6b2d9622d6832dd225/CHANGELOG.md?plain=1#L18

**Comment by pellared** [comment]
nit: Do we have any rules saying what should be the new version number? I thought that this would rather be a `0.2.1` as there are no breaking changes. My assumption was taken from a rule that we have in .NET auto-instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/versioning.md#version-numbers-before-100 Do we want to follow a similar pattern?

**Comment by MikeGoldsmith** [comment]
I did consider removing it from the changelog because it is not a functional change but as it didn't have skip changelog it was kept. I'm happy to remove it.

I'm also okay to set version as 0.2.1-alpha. I don't think versions mean all that much at the moment. Regarding no breaking changes, there wasn't any breaking changes when we went from 0.1 to 0.2, I think we did it to help signify the bump in compatibility (arm support) & features (gin support).

**Review by MrAlias — COMMENTED** [review]
Can we add a changelog entry for this: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/152?

**Comment by MrAlias** [comment]
This looks ready to merge: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/154 

Should we merge it before this to include it in the release?

**Review by MrAlias — APPROVED** [review]

**Comment by pellared** [comment]
> Regarding no breaking changes, there wasn't any breaking changes when we went from 0.1 to 0.2, I think we did it to help signify the bump in compatibility (arm support) & features (gin support).

This is not true. We did one user-facing breaking change: https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/b29eef681a0b3865c4f1948512f07c033dabe8c7/CHANGELOG.md?plain=1#L35-L36

**Pull request merged**
