### PR TITLE
Skip checking extra functions in FilterUnusedProbes()

### PR DESCRIPTION
**Pull request by damemi**
Once we find one of the symbols for a probe, we don't need to keep checking (we know we'll use that probe).

### CODE REVIEW

**Review by MrAlias — COMMENTED** [review]
Shouldn't we check that `funcsFound == len(inst.Manifest().Symbols)`? The way it currently is it will panic if there is any missing, right?

**Comment by RonFed** [comment]
> Shouldn't we check that `funcsFound == len(inst.Manifest().Symbols)`? The way it currently is it will panic if there is any missing, right?

It was changed after  https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/554

**Review by RonFed — APPROVED** [review]

**Comment by damemi** [comment]
> > Shouldn't we check that `funcsFound == len(inst.Manifest().Symbols)`? The way it currently is it will panic if there is any missing, right?
> 
> It was changed after #554

is there a test for that panic?

**Comment by RonFed** [comment]
> > > Shouldn't we check that `funcsFound == len(inst.Manifest().Symbols)`? The way it currently is it will panic if there is any missing, right?
> 
> > 
> 
> > It was changed after #554
> 
> 
> 
> is there a test for that panic?

Don't think so.

**Comment by damemi** [comment]
Ok, let's hold this then and I'll see if it's feasible to add a test for that

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
Plan is to track the error case testing in a follow-up issue.

**Pull request merged**
