### PR TITLE
Upgrade go-licenses from v1.6.0 to v2.0.0-alpha.1

### PR DESCRIPTION
**Pull request by MrAlias**
Includes upgrade of github.com/otiai10/copy that is blocking the upgrade of golangci-lint.

### CODE REVIEW

**Comment by MrAlias** [comment]
This will unblock https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/890

**Comment by MrAlias** [comment]
cc @damemi

**Comment by damemi** [comment]
Looks like nothing broke, @MrAlias I'm good merging this if you are

**Review by damemi — APPROVED** [review]

**Comment by MrAlias** [comment]
@grcevski @RonFed: thoughts?

**Review by RonFed — APPROVED** [review]

**Comment by damemi** [comment]
x-ref https://github.com/google/go-licenses/issues/235

**Pull request merged**
