### PR TITLE
Detect if the Linux Kernel is in lockdown mode

### PR DESCRIPTION
**Pull request by grcevski**
This PR adds a Linux Kernel lockdown mode validation check for the two bpf programs which use bpf_probe_write_user. If the kernel is running in lockdown mode (typically auto-enabled with Secure Boot), we now put an explanatory error message instead of 'failed to load bpf program error'.

Relates to https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/290

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Comment by edeNFed** [comment]
I am not sure we should completely not load the instrumentation in case the kernel is in lockdown mode.
For example, process-internal context propagation would still work. 

What do you think about producing spans and adding an error to them that specify something like `context propagation failed please change kernel lockdown mode`. I think this can be a good tradeoff between producing the best data that we can during kernel lockdown but also not confusing the users with a log message they will not find.

**Comment by grcevski** [comment]
Sure, I think I can do that. The only way I've been able to do this kind of thing is by using defines, compiling different versions of the BPF programs and loading selectively. I know about the `bpf_core_enum_value_exists` helper, but I've never been able to use it successfully, the verifier complains regardless of the `if` statement. Does this make sense, or do you have another approach in mind?

**Comment by MrAlias** [comment]
@edeNFed what do you think about doing that in a follow up PR?

**Comment by grcevski** [comment]
I'm happy to work on extending this PR and following with another that does the partial trace support. It will be easier for review if we are doing it incrementally, but I don't mind to extend this one if that's preferred.

**Comment by edeNFed** [comment]
@grcevski @MrAlias I am good with both options. Whatever easier for you.

**Review by edeNFed — APPROVED** [review]

**Pull request merged**
