### PR TITLE
Change OTEL_TARGET_EXE to OTEL_GO_AUTO_TARGET_EXE

### PR DESCRIPTION
**Pull request by pellared**
Fixes https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/96

### CODE REVIEW

**Comment by pellared** [comment]
Needs https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/95 😉

**Comment by pdelewski** [comment]
LGTM, however I'm thinking whether TARGET_EXE is best name for this variable

**Comment by pellared** [comment]
> LGTM, however I'm thinking whether TARGET_EXE is best name for this variable

We can change it if you have a better proposal. However, I would prefer to tackle it in a separate PR. This PR is about using the `OTEL_GO_AUTO_` prefix.

**Comment by pdelewski** [comment]
@pellared Agree, prefix fullfil spec requirements.

**Review by MikeGoldsmith — APPROVED** [review]
Thanks @pellared 👍🏻

**Comment by MikeGoldsmith** [comment]
@pellared #95 has merged, this can be rebased on now 😄

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
